Table usuario [headercolor: #175e7a] {
	id_usuario integer [ pk, increment, not null ]
	nombres varchar(100) [ not null ]
	apellidos varchar(100) [ not null ]
	correo_electronico varchar(150) [ not null, unique ]
	fecha_registro date [ not null ]
	salario_mensual_base numeric(12,2) [ not null ]
	estado boolean [ not null, default: true ]
	creado_por varchar(50) [ not null ]
	modificado_por varchar(50)
	creado_en timestamp [ not null ]
	modificado_en timestamp
}

Table categoria [headercolor: #175e7a] {
	id_categoria integer [ pk, increment, not null ]
	id_usuario integer [ not null ]
	nombre varchar(100) [ not null ]
	descripcion varchar(255) [ not null ]
	tipo varchar(10) [ not null ]
	icono varchar(50)
	color_hex char(7)
	orden_presentacion smallint [ not null, default: 0 ]
	creado_por varchar(50) [ not null ]
	modificado_por varchar(50)
	creado_en timestamp [ not null ]
	modificado_en timestamp
}

Table subcategoria [headercolor: #175e7a] {
	id_subcategoria integer [ pk, increment, not null ]
	id_categoria integer [ not null ]
	nombre varchar(100) [ not null ]
	descripcion varchar(255) [ not null ]
	activa boolean [ not null ]
	es_default boolean [ not null ]
	creado_por varchar(50) [ not null ]
	modificado_por varchar(50)
	creado_en timestamp [ not null ]
	modificado_en timestamp
}

Table presupuesto [headercolor: #175e7a] {
	id_presupuesto integer [ pk, increment, not null ]
	id_usuario integer [ not null ]
	nombre varchar(100) [ not null ]
	anio_inicio smallint [ not null ]
	mes_inicio smallint [ not null ]
	anio_fin smallint [ not null ]
	mes_fin smallint [ not null ]
	total_ingresos_planificados numeric(12,2) [ not null ]
	total_gastos_planificados numeric(12,2) [ not null ]
	total_ahorro_planificado numeric(12,2) [ not null ]
	fecha_hora_creacion timestamp [ not null ]
	estado varchar(10) [ not null ]
	creado_por varchar(50) [ not null ]
	modificado_por varchar(50)
	creado_en timestamp [ not null ]
	modificado_en timestamp
}

Table presupuesto_detalle [headercolor: #175e7a] {
	id_detalle integer [ pk, increment, not null ]
	id_presupuesto integer [ not null ]
	id_subcategoria integer [ not null ]
	monto_mensual numeric(12,2) [ not null ]
	observaciones varchar(255)
	creado_por varchar(50) [ not null ]
	modificado_por varchar(50)
	creado_en timestamp [ not null ]
	modificado_en timestamp
}

Table obligacion_fija [headercolor: #175e7a] {
	id_obligacion integer [ pk, increment, not null ]
	id_usuario integer [ not null ]
	id_subcategoria integer [ not null ]
	nombre varchar(100) [ not null ]
	descripcion varchar(255) [ not null ]
	monto_fijo_mensual numeric(12,2) [ not null ]
	dia_vencimiento smallint [ not null ]
	vigente boolean [ not null ]
	fecha_inicio date [ not null ]
	fecha_fin date
	creado_por varchar(50) [ not null ]
	modificado_por varchar(50)
	creado_en timestamp [ not null ]
	modificado_en timestamp
}

Table transaccion [headercolor: #175e7a] {
	id_transaccion integer [ pk, increment, not null ]
	id_usuario integer [ not null ]
	id_presupuesto integer [ not null ]
	anio smallint [ not null ]
	mes smallint [ not null ]
	id_subcategoria integer [ not null ]
	id_obligacion integer
	tipo varchar(10) [ not null ]
	descripcion varchar(255) [ not null ]
	monto numeric(12,2) [ not null ]
	fecha date [ not null ]
	metodo_pago varchar(20) [ not null ]
	numero_factura varchar(50)
	observaciones varchar(255)
	fecha_hora_registro timestamp [ not null ]
	creado_por varchar(50) [ not null ]
	modificado_por varchar(50)
	creado_en timestamp [ not null ]
	modificado_en timestamp
}

Ref fk_presupuesto_id_usuario_usuario {
	presupuesto.id_usuario - usuario.id_usuario [ delete: no action, update: no action ]
}

Ref fk_categoria_id_usuario_usuario {
	categoria.id_usuario - usuario.id_usuario [ delete: no action, update: no action ]
}

Ref fk_subcategoria_id_categoria_categoria {
	subcategoria.id_categoria - categoria.id_categoria [ delete: no action, update: no action ]
}

Ref fk_transaccion_id_usuario_usuario {
	transaccion.id_usuario - usuario.id_usuario [ delete: no action, update: no action ]
}

Ref fk_transaccion_id_presupuesto_presupuesto {
	transaccion.id_presupuesto - presupuesto.id_presupuesto [ delete: no action, update: no action ]
}

Ref fk_presupuesto_detalle_id_presupuesto_presupuesto {
	presupuesto_detalle.id_presupuesto - presupuesto.id_presupuesto [ delete: no action, update: no action ]
}

Ref fk_presupuesto_detalle_id_subcategoria_subcategoria {
	presupuesto_detalle.id_subcategoria - subcategoria.id_subcategoria [ delete: no action, update: no action ]
}

Ref fk_obligacion_fija_id_usuario_usuario {
	obligacion_fija.id_usuario - usuario.id_usuario [ delete: no action, update: no action ]
}

Ref fk_obligacion_fija_id_subcategoria_subcategoria {
	obligacion_fija.id_subcategoria - subcategoria.id_subcategoria [ delete: no action, update: no action ]
}

Ref fk_transaccion_id_obligacion_obligacion_fija {
	transaccion.id_obligacion - obligacion_fija.id_obligacion [ delete: no action, update: no action ]
}

Ref fk_transaccion_id_subcategoria_subcategoria {
	transaccion.id_subcategoria - subcategoria.id_subcategoria [ delete: no action, update: no action ]
}